# Generated by Django 6.1 on 2026-08-31 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=100)),
                ('failure_reason', models.CharField(max_length=300)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('at_risk', 'At Risk'), ('recovered', 'Recovered'), ('pending', 'Pending')], default='at_risk', max_length=20)),
                ('transaction_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('ai', 'AI Analysis'), ('policy', 'Policy'), ('action', 'Action'), ('success', 'Success'), ('review', 'Human Review')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='recovery.payment')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('policy_allowed', models.BooleanField(default=False)),
                ('policy_reason', models.TextField(blank=True)),
                ('requires_human_approval', models.BooleanField(default=False)),
                ('recovery_status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('recovered', 'Recovered'), ('human_review', 'Human Review')], default='waiting', max_length=30)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_case', to='recovery.payment')),
            ],
        ),
    ]
