# Generated by Django 6.1 on 2026-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycase',
            name='recovery_status',
            field=models.CharField(choices=[('analyzing', 'Analyzing'), ('waiting', 'Waiting for Execution'), ('in_progress', 'Recovery In Progress'), ('recovered', 'Recovered'), ('human_review', 'Human Review Required')], default='waiting', max_length=30),
        ),
    ]
