# Generated by Django 6.1 on 2026-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_alter_recoverycase_recovery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycase',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
